import React from 'react';
import {Easing,interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import {BOARD_STATES} from '../../lesson07-board-states';
import {BigCopy,BoardStage,Header,Scene,boxCenter} from '../components';
import {palette} from '../../Board';

export const Hook:React.FC=()=>{const frame=useCurrentFrame();return <Scene duration={120} dark><div style={{position:'absolute',inset:'0 78px',display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontFamily:'Arial, sans-serif',fontSize:25,letterSpacing:3,color:palette.gold,marginBottom:35}}>WHEN THE BRANCH HOLDS</div><div style={{fontSize:105,lineHeight:1.02,fontWeight:700}}>What if the branch<br/><span style={{color:palette.gold}}>doesn’t break?</span></div><div style={{width:interpolate(frame,[30,100],[0,760],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)}),height:7,background:palette.crimson,marginTop:58}} /></div></Scene>};

export const Setup:React.FC=()=>{const frame=useCurrentFrame();return <Scene duration={150}><Header/><div style={{position:'absolute',top:225,left:80,right:80}}><BigCopy kicker="SETUP" title="An Extreme puzzle." body="A few cross-hatching moves set the stage."/></div><div style={{position:'absolute',left:100,top:710,scale:interpolate(frame,[10,70],[.88,1],{extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)})}}><BoardStage state={BOARD_STATES[0]} dim={880}/></div></Scene>};

export const Confined:React.FC=()=>{const frame=useCurrentFrame();return <Scene duration={180}><Header/><div style={{position:'absolute',top:225,left:80,right:80}}><BigCopy kicker="THE FIRST CONSTRAINT" title="A confined 1–7 group." body="Two digits. Two cells. Less freedom everywhere else."/></div><div style={{position:'absolute',left:100,top:740}}><BoardStage state={BOARD_STATES[1]} dim={880}/></div><div style={{position:'absolute',left:510,top:1170,width:195,height:95,border:`9px solid ${palette.crimson}`,borderRadius:22,opacity:interpolate(frame,[45,75],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),scale:interpolate(frame,[45,75],[1.2,1],{extrapolateRight:'clamp'})}}/></Scene>};

export const Fork:React.FC=()=>{const frame=useCurrentFrame();const choose=interpolate(frame,[45,110],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)});return <Scene duration={180}><Header/><div style={{position:'absolute',top:225,left:80,right:80}}><BigCopy kicker="THE FORK" title="Two homes for 2." body="Choose the branch at r1c7. Then follow what it forces."/></div><div style={{position:'absolute',left:100,top:740}}><BoardStage state={BOARD_STATES[1]} dim={880} path={['r1c8','r1c7']} pathProgress={choose}/></div><div style={{position:'absolute',top:1660,left:80,right:80,fontFamily:'Arial, sans-serif',fontSize:36,textAlign:'center',color:palette.crimson,fontWeight:700,letterSpacing:1,opacity:choose}}>ASSUME r1c7 = 2</div></Scene>};

export const Branch:React.FC=()=>{const frame=useCurrentFrame();const path=['r1c7','r4c9','r5c8','r6c8','r6c7'] as const;return <Scene duration={330}><Header/><div style={{position:'absolute',top:225,left:80,right:80}}><BigCopy kicker="FOLLOW THE CHAIN" title={frame<190?'The branch continues.':'The branch holds.'} body={frame<190?'Box 6 resolves forward—one consequence at a time.':'No duplicate. No dead end. No contradiction.'}/></div><div style={{position:'absolute',left:100,top:750}}><BoardStage state={BOARD_STATES[2]} dim={880} path={path} pathProgress={interpolate(frame,[35,210],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)})}/></div></Scene>};

export const Parallel:React.FC=()=>{const frame=useCurrentFrame();const progress=interpolate(frame,[25,135],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});return <Scene duration={240}><Header/><div style={{position:'absolute',top:225,left:80,right:80}}><BigCopy kicker="PARALLEL CONTROL" title="7 controls 7." body="Boxes 2 and 5 align. Box 8 inherits the consequence."/></div><div style={{position:'absolute',left:100,top:750}}><BoardStage state={frame<135?BOARD_STATES[3]:BOARD_STATES[4]} dim={880} path={['r1c8','r2c5','r5c5','r9c4']} pathProgress={progress}/></div><div style={{position:'absolute',left:338,top:1570,fontFamily:'Arial, sans-serif',fontSize:31,color:palette.crimson,fontWeight:800,opacity:interpolate(frame,[125,165],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}>BOX 8 → r9c4 = 7</div></Scene>};

export const Completion:React.FC=()=>{const frame=useCurrentFrame();return <Scene duration={180}><Header/><div style={{position:'absolute',top:225,left:80,right:80}}><BigCopy kicker="THE BRANCH HOLDS" title="The grid completes." body="Singleton notes settle into committed digits."/></div><div style={{position:'absolute',left:100,top:740}}><BoardStage state={BOARD_STATES[5]} dim={880} resolveNotes={frame>85}/></div><div style={{position:'absolute',inset:'700px 80px auto',height:950,background:palette.cream,opacity:interpolate(frame,[70,100,130,165],[0,.1,.1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),pointerEvents:'none'}}/></Scene>};

export const Question:React.FC=()=>{return <Scene duration={90} dark><div style={{position:'absolute',inset:'0 80px',display:'flex',flexDirection:'column',justifyContent:'center',textAlign:'center'}}><BigCopy kicker="COMPLETION IS NOT ENOUGH" title="But is it correct?" dark align="center"/></div></Scene>};

export const Verification:React.FC=()=>{const frame=useCurrentFrame();const twos=['r1c7','r6c8','r9c9','r7c5','r8c2','r4c1','r2c3','r3c6','r5c4'] as const;return <Scene duration={150}><Header/><div style={{position:'absolute',top:215,left:80,right:80}}><BigCopy kicker="CIRCULAR VERIFICATION" title="Begin again with 2." body="Trace the digit box by box. Check every row and column."/></div><div style={{position:'absolute',left:100,top:735}}><BoardStage state={BOARD_STATES[5]} dim={880} resolveNotes path={twos} pathProgress={interpolate(frame,[18,125],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.bezier(.45,0,.55,1)})}/></div></Scene>};

export const EndCard:React.FC=()=>{const frame=useCurrentFrame();return <Scene duration={180} dark><div style={{position:'absolute',inset:'100px 78px',display:'flex',flexDirection:'column',alignItems:'center',textAlign:'center'}}><div style={{fontFamily:'Arial, sans-serif',fontSize:24,letterSpacing:4,color:palette.gold,marginTop:35}}>VERIFIED</div><div style={{width:170,height:170,border:`8px solid ${palette.crimson}`,borderRadius:'50%',display:'grid',placeItems:'center',fontFamily:'Arial, sans-serif',fontSize:82,fontWeight:800,color:palette.cream,marginTop:28,scale:interpolate(frame,[8,45],[.5,1],{extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)})}}>✓</div><div style={{fontSize:75,fontWeight:700,lineHeight:1.04,marginTop:54}}>The branch held.</div><div style={{fontSize:34,lineHeight:1.42,color:'#DCE8DC',marginTop:24}}>A real solve.<br/>Studied from its Su-Pu.</div><div style={{width:120,height:5,background:palette.gold,margin:'58px 0 44px'}}/><div style={{fontFamily:'Arial, sans-serif',fontSize:37,fontWeight:900,letterSpacing:4}}>ORBACE SUDOKU</div><div style={{fontFamily:'Arial, sans-serif',fontSize:31,lineHeight:1.45,marginTop:25}}>Study the solve.<br/>Play your own.<br/>Keep your Su-Pu.</div><div style={{marginTop:'auto',fontFamily:'Arial, sans-serif',fontSize:24,letterSpacing:2,color:'#DCE8DC'}}>一局一茶 · ONE PUZZLE, ONE TEA</div></div></Scene>};
